name: kiosk_flutter
description: "MEYPARK IA - Kiosko Flutter (Linux + Web)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Routing
  go_router: ^12.1.3

  # Supabase
  supabase_flutter: ^2.0.0

  # Internationalization
  intl: ^0.19.0

  # Accessibility
  flutter_tts: ^3.8.5

  # Platform detection
  universal_io: ^2.2.2

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6

  # Window management (Linux)
  window_manager: ^0.3.7

  # File handling
  file_selector: ^1.0.4

  # HTTP requests
  dio: ^5.4.0

  # Logging
  talker: ^3.1.0

  # Models
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1

  # Shared core (nuestro paquete)
  shared_core:
    path: ../../packages/shared_core

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Testing
  integration_test:
    sdk: flutter
  golden_toolkit: ^0.15.0

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700